### ISSUE TITLE
not full screen?

### ISSUE THREAD

**Issue by davemilter** [OlivierLDff/QtIosCMake#5]
It basically works. I update my demo project  https://github.com/davemilter/qt_ios_libs_bug.

But strange thing that the project looks different if compile with cmake and qmake. 
The qmake project have no mention of full screen or something, it is just few lines: https://github.com/davemilter/qt_ios_libs_bug/blob/master/foo.pro

![IMG_0188 PNG](https://user-images.githubusercontent.com/26097083/80092623-c1f0cc80-856b-11ea-8d25-2f1974858fce.jpeg)
![IMG_0187 PNG](https://user-images.githubusercontent.com/26097083/80092636-c6b58080-856b-11ea-9736-ab8e5a2f2d46.jpeg)

The same thing with https://github.com/OlivierLDff/QQuickStaticHelloWorld .

Is this because of basic plist is different? May be use the same by default that uses qmake ?

**Comment by OlivierLDff** [comment]
QMake is doing of stuff under the hood for you. It's kind of hard to know everything to mimic. What is you testing emulator? iPad?

`add_qt_ios_app` have lot's of options, maybe i should put some as default.
I think you should have a look to 
SUPPORT_IPHONE
SUPPORT_IPAD
REQUIRES_FULL_SCREEN

**Comment by OlivierLDff** [comment]
`SUPPORT_IPAD` was what was missing from my testing.
I changed the default to Universal instead of iPhone, so default function call will work as qmake.
Is it doing the trick for you?
db1e2084703816249a3c89ffff24c3c2558b1dbf

**Comment by davemilter** [comment]
> What is you testing emulator? iPad?

I just use my real iPad, no emulators.

**Comment by OlivierLDff** [comment]
Ok i don't have any ios stuff with because of corona, but the new default is working for me in iPad emulator. Is it working for you?

**Comment by davemilter** [comment]
It is working on real iPad. Full screen the same as qmake.

But Xcode gives warning during compilation: 

All interface orientations must be supported unless the app requires full screen.

The code that I tried: https://github.com/davemilter/qt_ios_libs_bug

**Comment by OlivierLDff** [comment]
Yes this is normal since you are not putting any of those flags:
* ORIENTATION_PORTRAIT
* ORIENTATION_PORTRAIT_UPSIDEDOWN
* ORIENTATION_LANDSCAPELEFT
* ORIENTATION_LANDSCAPERIGHT
* REQUIRES_FULL_SCREEN

Checkout the readme of this repository to choose the one that fit your need. And i don't think of those flags should be default. It's up to the user of `qt_add_ios_app` to set the option he needs.

I you check you cmake log, i raise also lots of warnings about options you are not setting.

So you have 2 choices, either you set the flag in your CMakeLists.txt:
```cmake
add_qt_ios_app(foo
ORIENTATION_PORTRAIT
ORIENTATION_PORTRAIT_UPSIDEDOWN
ORIENTATION_LANDSCAPELEFT
# ...
)
```

Or you fix them by hand once xcode project is loaded.

**Comment by OlivierLDff** [comment]
I consider the issue close. Feel free to reopen if more question.
